# Managed by sc-lint; regenerate with `sc-lint init --just`.
# Product-owned Windows consumer bootstrap. Generated by `sc-lint init --just`.
[CmdletBinding()]
param(
    [Parameter(Position = 0, Mandatory = $true)]
    [ValidateSet("ensure", "setup", "upgrade")]
    [string]$Operation
)

$configIndex = [Array]::IndexOf($args, "--config")
if ($configIndex -lt 0 -or $configIndex -eq ($args.Count - 1)) {
    [Console]::Error.WriteLine("usage: .sc-lint/bootstrap.ps1 <ensure|setup|upgrade> --config sc-lint.toml [--check] [--dry-run]")
    exit 2
}
$Config = $args[$configIndex + 1]
$remaining = @()
for ($argumentIndex = 0; $argumentIndex -lt $args.Count; $argumentIndex++) {
    if ($argumentIndex -ne $configIndex -and $argumentIndex -ne ($configIndex + 1)) {
        $remaining += $args[$argumentIndex]
    }
}
if ($remaining | Where-Object { $_ -notin @("--check", "--dry-run") }) {
    [Console]::Error.WriteLine("usage: .sc-lint/bootstrap.ps1 <ensure|setup|upgrade> --config sc-lint.toml [--check] [--dry-run]")
    exit 2
}
$Check = $remaining -contains "--check"
$DryRun = $remaining -contains "--dry-run"

$binary = if ($env:SC_LINT_BIN) { $env:SC_LINT_BIN } else { "sc-lint" }
$resolved = Get-Command $binary -ErrorAction SilentlyContinue
if (-not $resolved) {
    [Console]::Error.WriteLine("compatibility.check: could not find sc-lint binary ``$binary`` (CLI.SC_LINT_BINARY_NOT_FOUND)")
    [Console]::Error.WriteLine("Run ``just setup`` (or your repository's sc-lint installer) to create or repair a compatible installation.")
    [Console]::Error.WriteLine("Docs: sc-lint docs setup")
    exit 5
}

switch ($Operation) {
    "ensure" {
        & $binary --config $Config compatibility check --binary $binary
        if ($LASTEXITCODE -eq 0) { exit 0 }
        & $binary --config $Config setup
    }
    "setup" {
        $arguments = @("--config", $Config, "setup")
        if ($DryRun) { $arguments += "--dry-run" }
        & $binary @arguments
    }
    "upgrade" {
        $arguments = @("--config", $Config, "upgrade")
        if ($Check) { $arguments += "--check" }
        if ($DryRun) { $arguments += "--dry-run" }
        & $binary @arguments
    }
}
exit $LASTEXITCODE
